baseURL = "https://bkkcast.me/"
languageCode = "jp"
title = "bkkcast"
hasCJKLanguage = true

[params]
  description = "バンコクで働くエンジニアを集めて、バンコクの生活事情、最近エンジニア界隈で話題になったニュースなどについて話し合います。"
  eyecatch = "img/eyecatch.png"

[menu]

  [[menu.main]]
    identifier = "twitter"
    name = "@bkkcast"
    url = "https://twitter.com/bkkcast"
    weight = -110

[social]
  twitter = "bkkcast"
